# Generated by Django 4.2.7 on 2024-10-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('number', models.EmailField(max_length=255, null=True)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('delivery_date', models.DateField(null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('order_status', models.CharField(max_length=200, null=True)),
                ('Image', models.ImageField(null=True, upload_to='post-image')),
                ('moving', models.BooleanField(default=False, null=True)),
                ('ready', models.BooleanField(default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
