# Generated by Django 4.2.7 on 2024-10-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Shipment',
        ),
    ]
