# Generated by Django 4.2.7 on 2024-10-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_rename_item_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
