# Generated by Django 4.2.7 on 2024-10-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_shipment_tracking_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='Image',
            new_name='image',
        ),
    ]
