# Generated by Django 4.2.7 on 2024-10-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='country',
            new_name='current_country',
        ),
        migrations.AddField(
            model_name='shipment',
            name='from_country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
