# Generated by Django 4.2.7 on 2024-12-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_rename_country_shipment_current_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='current_country',
            new_name='receiver_name',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post-image'),
        ),
    ]
